name: Test run ZOHO

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master  # Ensure it checks out the master branch
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Script
        env:
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
          ZOHO_BASE_URL: ${{ secrets.ZOHO_BASE_URL }}
          ZOHO_SIGNIN_PAGE: ${{ secrets.ZOHO_SIGNIN_PAGE }}
        run: node zoho.js
